use crate::install::{LeptosInstaller, TailwindInstaller, TrunkInstaller};
use crate::project::ProjectDetector;
use anyhow::{Context, Result};
use colored::Colorize;
use std::env;
use std::fs;

pub fn execute() -> Result<()> {
    println!("{}", "Initializing leptos-daisyui-rs...".bold().green());
    println!();

    // 1. Detect project structure
    let current_dir = env::current_dir()?;
    let project = ProjectDetector::detect(&current_dir)
        .context("Failed to detect project structure. Are you in a Rust project?")?;

    println!("{} Detected project at: {}", "✓".green(), project.root().display());
    println!();

    // 2. Check leptos dependency
    check_leptos_dependency(&project)?;

    // 3. Check trunk installation
    check_trunk_installation()?;

    // 4. Check tailwindcss setup
    check_tailwindcss_setup(&project)?;

    // 5. Initialize src/generated directory
    initialize_generated_directory(&project)?;

    println!();
    println!("{}", "✓ Initialization complete!".bold().green());
    println!();
    println!("Next steps:");
    println!("  1. Run {} to see available components", "leptos-daisyui list --all".cyan());
    println!("  2. Run {} to add components", "leptos-daisyui add <component>".cyan());

    Ok(())
}

fn check_leptos_dependency(project: &crate::project::ProjectStructure) -> Result<()> {
    if LeptosInstaller::check_installed(project)? {
        println!("{} leptos dependency found", "✓".green());
    } else {
        LeptosInstaller::install()?;
    }

    Ok(())
}

fn check_trunk_installation() -> Result<()> {
    if TrunkInstaller::check_installed() {
        println!("{} trunk is installed", "✓".green());
    } else {
        TrunkInstaller::install()?;
    }

    Ok(())
}

fn check_tailwindcss_setup(project: &crate::project::ProjectStructure) -> Result<()> {
    let root = project.root();

    if TailwindInstaller::check_installed(root) {
        println!("{} Tailwind CSS and daisyUI found in package.json", "✓".green());
    } else {
        TailwindInstaller::setup(root)?;
    }

    Ok(())
}

fn initialize_generated_directory(project: &crate::project::ProjectStructure) -> Result<()> {
    let src_dir = ProjectDetector::find_main_binary_crate(project)?;
    let generated_dir = src_dir.join("generated");

    if generated_dir.exists() {
        println!("{} src/generated/ directory already exists", "✓".green());
        return Ok(());
    }

    // Create directory
    fs::create_dir_all(&generated_dir)
        .with_context(|| format!("Failed to create {}", generated_dir.display()))?;

    // Create mod.rs
    let mod_rs = generated_dir.join("mod.rs");
    let content = r#"//! Generated daisyUI components
//!
//! This module contains components generated by leptos-daisyui-cli.
//! Components can be added using: leptos-daisyui add <component>

"#;
    fs::write(&mod_rs, content)?;

    println!("{} Created src/generated/ directory", "✓".green());
    println!("{}", "  Don't forget to add to your lib.rs or main.rs:".dimmed());
    println!("{}", "    pub mod generated;".cyan());

    Ok(())
}

