[build]
target = "index.html"
release = false
dist = "dist"
public_url = "/"
filehash = true
inject_scripts = true


[watch]
watch = ["../src", "./src"]
ignore = []

[serve]
addresses = ["127.0.0.1"]
port = 3000
open = false

[[hooks]]
stage = "pre_build"
command = "npx"
command_arguments = ["tailwindcss", "-i", "input.css", "-o", "output.css"]
